<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.117.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValidadorScript.Application\ValidadorScript.Application.csproj" />
    <ProjectReference Include="..\ValidadorScript.Domain\ValidadorScript.Domain.csproj" />
  </ItemGroup>

</Project>
